# Tristan Tingey
# December 12th 2024
# Constellation Assignment for Computer Science Grade 11 Class.

# Imports turtle library
import turtle

# Makes the 500x by 500x window
turtle.Turtle()
turtle.setup(500, 500)
turtle.bgcolor("black")
turtle.pencolor("white")

# Star Variables at specefic coordinates.
star0 = (0,0)
turtle.penup()
turtle.goto(star0)
turtle.dot(5,"red")

star1 = (-50,48)
turtle.goto(star1)
turtle.dot(5,"white")

star2 = (-100,50)
turtle.goto(star2)
turtle.dot(5,"white")

star3 = (-160,47)
turtle.goto(star3)
turtle.dot(5,"white")

star4 = (-180,51)
turtle.goto(star4)
turtle.dot(5,"white")

star5 = (-145,10)
turtle.goto(star5)
turtle.dot(5,"white")

star6 = (-117,-20)
turtle.goto(star6)
turtle.dot(5,"white")

star7 = (-110,-29)
turtle.goto(star7)
turtle.dot(5,"white")

star8 = (-50,-50)
turtle.goto(star8)
turtle.dot(5,"white")

star9 = (20,-75)
turtle.goto(star9)
turtle.dot(5,"white")

star10 = (35,-55)
turtle.goto(star10)
turtle.dot(5,"white")

star11 = (120,85)
turtle.goto(star11)
turtle.dot(5,"white")

star12 = (125,123)
turtle.goto(star12)
turtle.dot(5,"white")

# Making the turtle go to the specific coordinates with the name being defined.
turtle.goto(star1)
name1 = turtle.write("Dorsum")
turtle.goto(-80, 60)
name2 = turtle.write("Nashira", move=False, align="left") 
turtle.goto(-140, 60)
name3 = turtle.write("Deneb Algedi", move=True, align="right") 
turtle.goto(-160, 70)
name4 = turtle.write("A Deneb Algedi")
turtle.goto(-145, 20)
name5 = turtle.write("K Castra")
turtle.goto(-114, -25)
name6 = turtle.write("E Castra")
turtle.goto(-100, -40)
name7 = turtle.write("Marakk")
turtle.goto(-60, -50)
name8 = turtle.write("Baten Algedi", move=False, align="left")
turtle.goto(50, -115) 
name9 = turtle.write("W Baten Algedi", move=False, align="right")
turtle.goto(35, -35)
name10 = turtle.write("Dabih")
turtle.goto(100, 90)
name11 = turtle.write("Algiedi", move=False, align="left")
turtle.goto(125, 135)
name12 = turtle.write("Alshat", move=False, align="right")

# Turtle drawing the lines to connect them together.
turtle.goto(star1)
turtle.pendown()
turtle.goto(star2)
turtle.penup()
turtle.goto(star2)
turtle.pendown()
turtle.goto(star3)
turtle.penup()
turtle.goto(star3)
turtle.pendown()
turtle.goto(star4)
turtle.penup()
turtle.goto(star4)
turtle.pendown()
turtle.goto(star5)
turtle.penup()
turtle.goto(star5)
turtle.pendown()
turtle.goto(star6)
turtle.penup()
turtle.goto(star6)
turtle.pendown()
turtle.goto(star7)
turtle.penup()
turtle.goto(star7)
turtle.pendown()
turtle.goto(star8)
turtle.penup()
turtle.goto(star8)
turtle.pendown()
turtle.goto(star9)
turtle.penup()
turtle.goto(star9)
turtle.pendown()
turtle.goto(star10)
turtle.penup()
turtle.goto(star10)
turtle.pendown()
turtle.goto(star11)
turtle.penup()
turtle.goto(star11)
turtle.pendown()
turtle.goto(star12)
turtle.penup()
turtle.goto(star12)
turtle.pendown()
turtle.goto(star11)
turtle.penup()
turtle.goto(star11)
turtle.pendown()
turtle.goto(star1)
turtle.penup()
turtle.goto(star1)
turtle.penup()

# End the turtle function
turtle.done()
